name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: building application
      run: |
        cd src
        mkdir build
        cd build
        cmake ..
        make
        ./interpreter
        cd ..
        rm -r build
