name: lox-interpreter-ci

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: building application
      run: |
        mkdir build
        cd build
        cmake ..
        make
        cd ..
        chmod +x run_tests.sh && ./run_tests.sh
        rm -r build
